version: '3.8'

services:
  api:
    container_name: lunch-voting-api
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/voting-app?schema=public
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db

  db:
    container_name: lunch-voting-db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=voting-app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 